post_install(){
  echo "==> Must install apacman-deps meta package to compile packages from AUR"
  echo "==> Remove build depends with: pacman -Rss apacman-deps"
}

post_upgrade() {
  echo "==> Must install apacman-deps meta package to compile packages from AUR"
  echo "==> Remove build depends with: pacman -Rss apacman-deps"
}

post_remove() {
  echo "==> Remove build depends with: pacman -Rss apacman-deps"
  userdel aurbuild 2>/dev/null
}
