#!/bin/bash
######################################################################
# apacman - AUR wrapper forked from packer
version="1.5"
# Copyright OS Hazard <oshazard+aur@gmail.com>
#
# New Features:
# * Config file support
# * Built-in ABS support (WIP)
# * Workaround for running as root
# * Saves AUR packages to /var/cache/apacman/pkg
# * Uses AUR package cache directory if applicable
# * --nosource    for security do not source PKGBUILDs (WIP)
# * --buildonly   create but do not install packages
# * --nofail      do not continue if a package fails to build
# * --purgebuild  remove unneeded build dependencies
# * --skiptest    skips installing check() unit test packages
# * --config      specify alternate config file (default: /etc/apacman.conf)
# * --verbose     turns on verbose output
# * -L            list installed packages by size
# * --noaur       do not actions for aur
# * --warn        treat errors as non-fatal warnings
# * --needed      does not install up-to-date packages
# * --ignorearch  ignores architectures specified in PKGBUILD
# * --skipcache   skips check for pre-built package in cache directory
# * --cachevcs    installs cached VCS (git, svn, hg) packages newer than AUR PKGBUILDs
# * partial passthrough for -R, -Q, -T and -U parameters
######################################################################

# Copyright Matthew Bruenig <matthewbruenig@gmail.com>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[[ $PACMAN ]] || PACMAN="pacman"
pacmanbin="/usr/bin/pacman"

makepkgconf='/etc/makepkg.conf'
usermakepkgconf="$HOME/.makepkg.conf"
pacmanconf='/etc/pacman.conf'
apacmanconf='/etc/apacman.conf'
downdir='/var/cache/pacman/pkg'
savedir='/var/cache/apacman/pkg'

editor="vi"
[[ $EDITOR ]] && editor="$EDITOR"

RPCURL="https://aur.archlinux.org/rpc.php?type"
PKGURL="https://aur.archlinux.org"
ABSURL="rsync.archlinux.org"

# set tmpfile stuff, clean tmpdir
tmpdir="${TMPDIR:-/tmp}/apacmantmp-$UID"
rm -rf "$tmpdir" &>/dev/null
mkdir -p "$tmpdir"

if [[ -t 1 && ! $COLOR = "NO" ]]; then
  COLOR1='\e[1;39m'
  COLOR2='\e[1;32m'
  COLOR3='\e[1;35m'
  COLOR4='\e[1;36m'
  COLOR5='\e[1;34m'
  COLOR6='\e[1;33m'
  COLOR7='\e[1;31m'
  ENDCOLOR='\e[0m' 
  S='\\'
fi
_WIDTH="$(stty size | cut -d ' ' -f 2)"

trap ctrlc INT
ctrlc() {
  echo
  exit
}

err() {
  echo -e "$1"
  [[ "$warn" == 1 ]] || exit 1
}

invalid() {
  echo -e "${COLOR7}error:${ENDCOLOR} invalid option \`$1'"
}

deptest() {
  type -p $1 &>/dev/null
}

version() {
  pacver=$($pacmanbin -V 2>/dev/null | grep -o "Pacman v.*")
  echo "   ===   =   =  =====     apacman v${version}  - forked from packer"
  echo "  =   =  =   =  =   =     ${pacver}"
  echo '  =====  =   =  ===='
  echo '  =   =  =   =  =   =     This program may be freely redistributed under'
  echo '  =   =   ===   =   =     the terms of the GNU General Public License.'
  exit
}

usage() {
  echo 'usage: apacman [option] [package] [package] [...]'
  echo
  echo '    -S           - installs package'
  echo '    -Syu|-Su     - updates all packages, also takes -uu and -yy options'
  echo '    -Ss|-Ssq     - searches for package'
  echo '    -Si          - outputs info for package'
  echo '    -G           - download and extract aur tarball only'
  echo '    -L           - list installed packages by size'
  echo
  echo '    --auronly    - only do actions for AUR'
  echo '    --buildonly  - create but do not install packages'
  echo '    --config     - specify alternate config file (default: /etc/apacman.conf)'
  echo '    --cachevcs   - installs cached VCS packages newer than AUR PKGBUILDs'
  echo '    --devel      - update VCS (git, svn, hg) packages during -Su'
  echo '    --ignore     - takes a comma-separated list of packages to ignore'
  echo '    --ignorearch - ignore a missing or incomplete architecture field'
  echo '    --needed     - do not install up-to-date packages'
  echo '    --noaur      - do not actions for AUR'
  echo '    --noconfirm  - do not prompt for any confirmation'
  echo '    --noedit     - do not prompt to edit files'
  echo '    --nofail     - do not continue if a package fails to build'
  echo '    --nosource   - do not source PKGBUILDs (WIP)'
  echo '    --preview    - edit pkgbuild before sourcing'
  echo '    --purgebuild - remove unneeded build dependencies'
  echo '    --quickcheck - check for updates and exit'
  echo '    --quiet      - only output package name for searches'
  echo '    --skipcache  - skips check for pre-built package in cache directory'
  echo '    --skipinteg  - when using makepkg, do not check md5s'
  echo '    --skiptest   - when using makepkg, do not parse check() test deps'
  echo '    --warn       - treat errors as non-fatal warnings'
  echo '    -v           - turns on verbose output'
  echo '    -V           - display version'
  echo '    -h           - outputs this message'
  exit
}

varstatus() {
  val=$(eval echo \$$1)
  if [ "$val" == 1 ]; then
    echo -e "${COLOR1}$1${ENDCOLOR}" | awk '{printf "%-25s %-40s\n",$1,": yes"}';
  elif [[ -r $val ]]; then
    echo -e "${COLOR1}$1${ENDCOLOR} $val" | awk '{printf "%-25s %-40s\n",$1,": "$2}';
  fi
}

infoconf() {
  vars="apacmanconf downdir editor makepkgconf pacmanconf savedir tmpdir usermakepkgconf"
  for i in $vars; do
    varstatus $i
  done

  vars="auronly buildonly cachevcs ignorearch needed noaur noconfirm noedit"
  vars="$vars nofail preview purgebuild quiet skipcache skipinteg skiptest warn"
  for j in $vars; do
    varstatus $j
  done
}

# Called whenever anything needs to be run as root ($@ is the command)
runasroot() {
  if [[ $UID -eq 0 ]]; then
    "$@"
  elif sudo -v &>/dev/null && sudo -l "$@" &>/dev/null; then
    sudo -E "$@"
  else
    echo -n "root "
    su -c "$(printf '%q ' "$@")"
  fi
}

# FIXME
parser() {
  if [ -f "$1" ]; then
    if [[ $nosource == 1 ]]; then
      unset pkgname pkgver pkgrel arch checkdepends makedepends depends
      pkgname=$(grep -o "^pkgname=\S*" "$1" | awk -F = '{print $2}' | tr -dc 'a-z0-9-_.\n');
      pkgver=$(grep -o "^pkgver=\S*" "$1" | awk -F = '{print $2}' | tr -dc 'a-z0-9-_.\n');
      pkgrel=$(grep -o "^pkgrel=\S*" "$1" | awk -F = '{print $2}' | tr -dc 'a-z0-9-_.\n');
      _arch=$(grep "^arch=" "$1" | awk -F = '{print $2}' | tr -dc 'a-z0-9-_. \n');
      _checkdepends=$(grep "^checkdepends=" "$1" | awk -F = '{print $2}' | tr -dc 'a-z0-9-_. \n');
      _makedepends=$(grep "^makedepends=" "$1" | awk -F = '{print $2}' | tr -dc 'a-z0-9-_. \n');
      _depends=$(grep "^depends=" "$1" | awk -F = '{print $2}' | tr -dc 'a-z0-9-_. \n');

      for _machine in $_arch; do arch+=("$_machine"); done
      for _pkg in $_checkdepends; do depends+=("$_pkg"); done
      for _pkg in $_makedepends; do makedepends+=("$_pkg"); done
      for _pkg in $_depends; do depends+=("$_pkg"); done

      echo "==> pkgname: $pkgname"
      echo "==> pkgver: $pkgver"
      echo "==> pkgrel: $pkgrel"
      echo "==> arch: ${arch[@]}"
      echo "==> checkdepends: ${checkdepends[@]}"
      echo "==> makedepends: ${makedepends[@]}"
      echo "==> depends: ${depends[@]}"
      return 0
    else
      . "$1"
    fi
  else
    return 1
  fi
}

# Source apacman.conf file
sourceapacmanconf() {
  [[ -r "$apacmanconf" ]] && . "$apacmanconf"
  [[ $noconfirm ]] && PACOPTS+=("--noconfirm")
  [[ $needed ]] && PACOPTS+=("--needed")
  [[ $skiptest ]] && MAKEPKGOPTS+=("--nocheck")
  [[ $skipinteg ]] && MAKEPKGOPTS+=("--skipinteg")
  [[ $ignorearch ]] && MAKEPKGOPTS+=("--ignorearch")
}

# Source makepkg.conf file
sourcemakepkgconf() {
  . "$makepkgconf"
  [[ -r "$usermakepkgconf" ]] && . "$usermakepkgconf"
}

# Parse IgnorePkg and --ignore, put in globally accessible ignoredpackages array
getignoredpackages() {
  IFS=',' read -ra ignoredpackages <<< "$ignorearg"
  ignoredpackages+=( $(grep '^ *IgnorePkg' "$pacmanconf" | cut -d '=' -f 2-) )
}

# Checks to see if $1 is an ignored package
isignored() {
  [[ " ${ignoredpackages[@]} " =~ " $1 " ]]
}

# List installed packages
getlistpackages() {
  $pacmanbin -Qi${pacmanarg} | grep -e "^Name " -e "^Installed Size " | \
  awk '{if ($(NF-1) ~ /^[0-9]/) printf $(NF-1); print $NF}' | paste -s -d' \n' | \
  sed -e 's/iB$//' -e 's/\.00K/K/' -e 's/\.00B/B/' | awk '{printf "%-10s %-40s\n",$2,$1}' | sort -h
}

# Tests whether $1 exists on the aur
existsinaur() {
  rpcinfo "$1"
  [[ "$(jshon -Qe resultcount -u < "$tmpdir/$1.info")" != "0" ]]
}

# Tests whether $1 exists in pacman
existsinpacman() {
  $pacmanbin -Si -- "$1" &>/dev/null
}

# Tests whether $1 is provided in pacman, sets globally accessibly providepkg var
providedinpacman() {
  unset providepkg
  IFS=$'\n' read -rd '' -a providepkg < <($pacmanbin -Ssq -- "^$1$")
  [[ -n $providepkg ]]
}

# Tests whether $1 exists in a pacman group
existsinpacmangroup() {
  [[ $($pacmanbin -Sgq "$1") ]]
}

# Tests whether $1 exists locally
existsinlocal() {
  $pacmanbin -Qq -- "$1" &>/dev/null
}

# Scrapes the aur deps from PKGBUILDS and puts in globally available dependencies array
scrapeaurdeps() {
  pkginfo "$1" "$preview"
  parser "$tmpdir/$1.PKGBUILD"
  [[ $skiptest = 1 ]] && unset checkdepends
  IFS=$'\n'
  dependencies=( $(echo -e "${depends[*]}\n${makedepends[*]}\n${checkdepends[*]}" | sed -e 's/=.*//' -e 's/>.*//' -e 's/<.*//'| sort -u) )
  purgedepends=( $(echo -e "${makedepends[*]}\n${checkdepends[*]}" | sed -e 's/=.*//' -e 's/>.*//' -e 's/<.*//'| sort -u) )
  unset IFS
}

# Finds dependencies of package $1
# Sets pacmandeps and aurdeps array, which can be accessed globally after function runs
finddeps() {
  # loop through dependencies, if not installed, determine if pacman or aur deps
  pacmandeps=()
  aurdeps=()
  scrapeaurdeps "$1"
  [[ $buildonly = 1 || $purgebuild = 1 ]] && purgedeps+=( $($pacmanbin -T "${purgedepends[@]}") )
  missingdeps=( $($pacmanbin -T "${dependencies[@]}") )
  while [[ $missingdeps ]]; do
    checkdeps=()
    for dep in "${missingdeps[@]}"; do
      if [[ " $1 ${aurdeps[@]} ${pacmandeps[@]} " =~ " $dep " ]];  then
        continue
      fi
      if existsinpacman "$dep"; then
        pacmandeps+=("$dep")
      elif existsinaur "$dep"; then
        if [[ $aurdeps ]]; then
          aurdeps=("$dep" "${aurdeps[@]}")
        else
          aurdeps=("$dep")
        fi
        checkdeps+=("$dep")
      elif providedinpacman "$dep"; then
        pacmandeps+=("$providepkg")
      else
        [[ $option = "install" ]] &&  err "Dependency \`$dep' of \`$1' does not exist."
        echo "Dependency \`$dep' of \`$1' does not exist."
        return 1
      fi
    done
    missingdeps=()
    for dep in "${checkdeps[@]}"; do
      scrapeaurdeps "$dep"
      for depdep in "${dependencies[@]}"; do
        [[ $($pacmanbin -T "$depdep") ]] && missingdeps+=("$depdep")
      done
    done
  done
  return 0
}

# Displays a progress bar ($1 is numerator, $2 is denominator, $3 is candy/normal)
aurbar() {
  # Delete line
  printf "\033[0G"
  
  # Get vars for output
  beginline=" aur"
  beginbar="["
  endbar="] "
  perc="$(($1*100/$2))"
  width="$(stty size)"
  width="${width##* }"
  charsbefore="$((${#beginline}+${#1}+${#2}+${#beginbar}+3))"
  spaces="$((51-$charsbefore))"
  barchars="$(($width-51-7))"
  hashes="$(($barchars*$perc/100))" 
  dashes="$(($barchars-$hashes))"

  # Print output
  printf "$beginline %${spaces}s$1  $2 ${beginbar}" ""

  # ILoveCandy
  if [[ $3 = candy ]]; then
    for ((n=1; n<$hashes; n++)); do
      if (( (n==($hashes-1)) && ($dashes!=0) )); then
        (($n%2==0)) && printf "\e[1;33mc\e[0m" || printf "\e[1;33mC\e[0m"
      else
        printf "-"
      fi
    done
    for ((n=1; n<$dashes; n++)); do
      N=$(( $n+$hashes ))
      (($hashes>0)) && N=$(($N-1))
      (($N%3==0)) && printf "o" || printf " "
    done
  else
    for ((n=0; n<$hashes; n++)); do
      printf "#"
    done
    for ((n=0; n<$dashes; n++)); do
      printf "-"
    done
  fi
  printf "%s%3s%%\r" ${endbar} ${perc}
}

rpcinfo() {
  if ! [[ -f "$tmpdir/$1.info" ]]; then
    curl -LfGs --data-urlencode "arg=$1" "$RPCURL=info" > "$tmpdir/$1.info"
  fi
}

pkglink() {
  rpcinfo $1
  echo "${PKGURL}$(jshon -Q -e results -e URLPath -u < "$tmpdir/$1.info")"
}

absrepo() {
  $pacmanbin -Si -- "$1" 2>/dev/null | grep ^Repository | awk '{print $NF}' | awk NR==1
}

# downloads source files ($1 is package repository, $2 is package name)
abslink() {
  deptest rsync || err "${COLOR7}error:${ENDCOLOR} $option requires \`rsync'"
  rflags="-mrt --info=progress2 --no-motd --delete-after --no-p --no-o --no-g"
  rsync $rflags --include=/$1{,/$2} --exclude=/{$1/,}* ${ABSURL}::abs/{${makearch},any}/ .
}

# downloads pkgbuild ($1), edits if $2 is set
pkginfo() {
  if ! [[ -f "$tmpdir/$1.PKGBUILD" ]]; then
    pkgpath=$(pkglink $1)
    curl -Lfs "${pkgpath%/*}/PKGBUILD" > "$tmpdir/$1.PKGBUILD"
    if [[ $2 ]]; then
      # rename for syntax highlighting
      cp "$tmpdir/$1.PKGBUILD" "$tmpdir/PKGBUILD"
      confirm_edit "${COLOR6}Edit $1 PKGBUILD with \$editor? [Y/n]${ENDCOLOR} " "$tmpdir/PKGBUILD"
      mv "$tmpdir/PKGBUILD" "$tmpdir/$1.PKGBUILD"
    fi
  fi
}

# Checks if package is newer on aur ($1 is package name, $2 is local version)
aurversionisnewer() {
  rpcinfo "$1"
  unset aurversion
  if existsinaur "$1"; then
    aurversion="$(jshon -Q -e results -e Version -u < "$tmpdir/$1.info")"
    if [[ "$(LC_ALL=C vercmp "$aurversion" "$2")" -gt 0  ]]; then
      return 0
    fi
  fi
  return 1
}

isoutofdate() {
  rpcinfo "$1"
  [[ "$(jshon -Q -e results -e OutOfDate -u < "$tmpdir/$1.info")" = "1" ]]
}

# List bundle package files
listbundle() {
  if [[ $bundle ]]; then
    echo -e "${COLOR5}==>${ENDCOLOR} Packages to bundle"
    echo ${bundle[@]} | sed 's/ /\n/g' | tee "$tmpdir/bundle.lst"
  fi
}

# $1 is prompt, $2 is file
confirm_edit() {
  if [[ (! -f "$2") || "$noconfirm" || "$noedit" ]]; then
    return
  fi
  echo -en "$1"
  if proceed; then
    $editor "$2"
  fi
}

# Output status of aur packages ($1 is 0 for success or 1 for failure)
buildstatus() {
  if [[ $1 != 0 ]]; then
    echo
    echo -e "${COLOR7}==> ERROR:${ENDCOLOR} ${COLOR1}the build failed${ENDCOLOR}"
  fi

  echo -ne "${COLOR5}  ->${ENDCOLOR} ${COLOR1}Status${ENDCOLOR}"
  [[ $success ]] && echo -ne "\t${COLOR4}built (${#success[@]}):${ENDCOLOR} ${success[@]}"
  [[ $failure ]] && echo -ne "\t${COLOR7}failed (${#failure[@]}):${ENDCOLOR} ${failure[@]}"
  echo ""

  [[ $nofail = 1 && $1 != 0 ]] && exit 1
}

# Build install ($1 is package, $2 is dependency or explicit, $3 is filename)
buildinstall() {
  if [[ $2 = dependency ]]; then
    runasroot $PACMAN ${PACOPTS[@]} --asdeps -U "$3"
    [[ $buildonly = 1 ]] && bundle+=("$3")
    [[ $buildonly = 1 ]] && purgedeps+=("$1")
  elif [[ $2 = explicit ]]; then
    [[ $buildonly = 1 ]] && echo -e "${COLOR6}notice:${ENDCOLOR} $1 built -- not installing"
    [[ $buildonly = 1 ]] && bundle+=("$3")
    [[ $buildonly != 1 ]] && runasroot $PACMAN ${PACOPTS[@]} -U "$3"
  fi
}

# Checks if aur cache is newer than aur ($1 is package, $2 is aur version)
checkvcs() {
  cachefile=$(ls -t ${savedir}/${1}-*-{any,${makearch}}.pkg.{tar,tar.xz} 2>/dev/null | awk NR==1 | awk -F "${savedir}/${1}-" '{print $2}');
  cachever=$(echo "$cachefile" | sed "s/-any.pkg.tar.xz//g;s/-any.pkg.tar//g;s/-${makearch}.pkg.tar.xz//g;s/-${makearch}.pkg.tar//g");
  if [[ "$(LC_ALL=C vercmp "$cachever" "$2")" -gt 0 ]]; then
    echo -e "${COLOR7}warning:${ENDCOLOR} $1 -- ${COLOR7}verify cache newer than AUR${ENDCOLOR} ($pkgver-$pkgrel)" 
    pkgfile="${savedir}/${1}-${cachefile}";
  elif [[ "$(LC_ALL=C vercmp "$cachever" "$2")" -eq 0 ]]; then
    pkgfile="${savedir}/${1}-${cachefile}";
  fi
}

# Checks if packages are in aur cache ($1 is package, $2 is dependency or explicit)
checkcache() {
  unset pkgfile;

  if [ "$skipcache" != "1" ]; then
    sourcemakepkgconf
    pkgfile=$(ls ${savedir}/${1}-${pkgver}-${pkgrel}-{any,${makearch}}.pkg.{tar,tar.xz} 2>/dev/null | awk NR==1);
  fi

  if [ "$cachevcs" = "1" ]; then
    checkvcs $1 $pkgver-$pkgrel
  fi

  if [ -f "$pkgfile" ]; then
    cacheinstall "$1" "$2" "$pkgfile"
  else
    aurinstall "$1" "$2"
  fi;
}

# Installs packages from cache ($1 is package, $2 is dependency or explicit, $3 is filename)
cacheinstall() {
  if [ "$cachevcs" = "1" ]; then
    pkgrelease="$1-$cachever"
  else
    pkgrelease="$1-$pkgver-$pkgrel"
  fi

  echo -e "${COLOR6}notice:$ENDCOLOR installing $pkgrelease from cache"
  buildinstall $1 $2 $3
}

# Installs packages from aur ($1 is package, $2 is dependency or explicit)
aurinstall() {
  dir="${TMPDIR:-/tmp}/pkgbuild-$UID/$1"
  sourcemakepkgconf

  # Prepare the installation directory
  # If there is an old directory and aurversion is not newer, use old directory
  if parser "$dir/$1/PKGBUILD" &>/dev/null && ! aurversionisnewer "$1" "$pkgver-$pkgrel"; then
    cd "$dir/$1"
  else
    [[ -d "$dir" ]] && rm -rf "$dir"
    mkdir -p "$dir"
    cd "$dir"
    curl -Lfs "$(pkglink $1)" > "$1.tar.gz"
    mkdir "$1"
    tar xf "$1.tar.gz" -C "$1" --strip-components=1
    cd "$1"
    if [[ $preview &&  -s "$tmpdir/$1.PKGBUILD" ]]; then
      cp "$tmpdir/$1.PKGBUILD" PKGBUILD
    fi
    # customizepkg
    if [[ -f "/etc/customizepkg.d/$1" ]] && deptest customizepkg; then
      echo "Applying customizepkg instructions..."
      customizepkg --modify
    fi
  fi

  # check for missing arch
  if [[ ! " ${arch[@]} " =~ " any " ]]; then
    if [[ ! " ${arch[@]} " =~ " ${CARCH} " ]]; then
      echo -e "${COLOR6}warning:$ENDCOLOR $CARCH missing from arch array"
    fi
  fi

  # Allow user to edit PKGBUILD
  confirm_edit "${COLOR6}Edit $1 PKGBUILD with \$editor? [Y/n]${ENDCOLOR} " PKGBUILD
  if ! [[ -f PKGBUILD ]]; then
    err "No PKGBUILD found in directory."
  fi

  # Allow user to edit .install
  unset install
  parser PKGBUILD
  confirm_edit "${COLOR6}Edit $install with \$editor? [Y/n]${ENDCOLOR} " "$install"

  # Installation (makepkg and pacman)
  rm -f *$PKGEXT
  if [[ $UID -eq 0 ]]; then
    id aurbuild >/dev/null 2>/dev/null || useradd -r -d /var/empty aurbuild
    chown -R aurbuild:aurbuild .
    su -c "makepkg $MAKEPKGOPTS -f" aurbuild
  else
    makepkg $MAKEPKGOPTS -f
  fi

  # Build check
  if [[ $? -ne 0 ]]; then
    failure+=("$1")
    buildstatus 1
  else
    success+=("$1")
    buildstatus 0
  fi

  pkgtarfiles=""
  for i in "${pkgname[@]}"; do
    pkgtarfiles="$pkgtarfiles $i-*$PKGEXT"
  done

  # Save packages
  pkgtar=$(ls $pkgname-*$PKGEXT 2>/dev/null | tail -n 1)
  if [[ $pkgtar ]]; then
    [ -d $savedir ] || runasroot mkdir -p $savedir
    runasroot cp $pkgname-*$PKGEXT $savedir/
    echo -e "${COLOR5}  -> ${COLOR1}Saved package:${ENDCOLOR} $(ls $pkgname-*$PKGEXT)";
    pkgfilename=$(ls $pkgname-*$PKGEXT)
    buildinstall $pkgname $2 ${savedir}/$pkgfilename
  fi
}

# Goes through all of the install tests and execution ($@ is packages to be installed)
installhandling() {
  packageargs=("$@")
  getignoredpackages
  sourcemakepkgconf
  # Figure out all of the packages that need to be installed
  for package in "${packageargs[@]}"; do
    # Determine whether package is in pacman repos
    if ! [[ $auronly ]] && existsinpacman "$package"; then
      pacmanpackages+=("$package")
    elif ! [[ $auronly ]] && existsinpacmangroup "$package"; then
      pacmanpackages+=("$package")
    elif ! [[ $noaur ]] && existsinaur "$package"; then
      if finddeps "$package"; then
        # here is where dep dupes are created
        aurpackages+=("$package")
        aurdepends=("${aurdeps[@]}" "${aurdepends[@]}")
        pacmandepends+=("${pacmandeps[@]}")
      fi
    else
      err "Package \`$package' does not exist."
    fi
  done

  # Check if any aur target packages are ignored
  for package in "${aurpackages[@]}"; do
    if isignored "$package"; then
      echo -ne "${COLOR5}:: ${COLOR1}$package is in IgnorePkg/IgnoreGroup. Install anyway?${ENDCOLOR} [Y/n] "
      if ! [[ $noconfirm ]]; then
        proceed || continue
      else
        echo
      fi
    fi
    aurtargets+=("$package")
  done

  # Check if any aur dependencies are ignored
  for package in "${aurdepends[@]}"; do
    if isignored "$package"; then
      echo -ne "${COLOR5}:: ${COLOR1}$package is in IgnorePkg/IgnoreGroup. Install anyway?${ENDCOLOR} [Y/n] "
      if ! [[ $noconfirm ]]; then
        if ! proceed; then
          echo "Unresolved dependency \`$package'"
          unset aurtargets
          break
        fi
      else
        echo
      fi
    fi
  done
 
  # First install the explicit pacman packages, let pacman prompt
  if [[ $pacmanpackages ]]; then
    echo -e "${COLOR6}Pacman Targets    ($((${#pacmanpackages[@]}))):${ENDCOLOR} ${pacmanpackages[@]}"
    echo
    if [[ $buildonly = 1 ]]; then
      downfile=$($PACMAN -Sp -- "${pacmanpackages[@]}" | awk -v dir=$downdir -F "/" '{print dir"/"$NF}')
      bundle+=("${downfile}")
      runasroot $PACMAN "${PACOPTS[@]}" -Sw --cachedir $downdir -- "${pacmanpackages[@]}"
    else
      runasroot $PACMAN "${PACOPTS[@]}" -S -- "${pacmanpackages[@]}"
    fi
  fi
  if [[ -z $aurtargets ]]; then
    listbundle
    exit
  fi

  # Test if aurpackages are already installed; echo warning if so
  for pkg in "${aurtargets[@]}"; do
    if existsinlocal "$pkg"; then
      localversion="$($pacmanbin -Qs "$pkg" | grep -F "local/$pkg " | cut -d ' ' -f 2)"
      if ! aurversionisnewer "$pkg" "$localversion"; then
        if [ "$needed" = "1" ]; then
          echo -e "${COLOR6}notice:$ENDCOLOR $pkg-$localversion is up to date -- skipping" 
          aurtargets=(${aurtargets[@]/$pkg/});
        else
          echo -e "${COLOR6}warning:$ENDCOLOR $pkg-$localversion is up to date -- reinstalling"
        fi
      fi
    fi
  done

  # Echo warning if packages are out of date
  for pkg in "${aurtargets[@]}" "${aurdepends[@]}"; do
    if isoutofdate "$pkg"; then
      echo -e "${COLOR6}warning:$ENDCOLOR $pkg is flagged out of date"
    fi
  done
    
  # Prompt for aur packages and their dependencies
  echo
  if [[ $aurdepends ]]; then
    num="$((${#aurdepends[@]}+${#aurtargets[@]}))"
    echo -e "${COLOR6}Aur Targets    ($num):${ENDCOLOR} ${aurdepends[@]} ${aurtargets[@]}"
  else 
    echo -e "${COLOR6}Aur Targets    ($((${#aurtargets[@]}))):${ENDCOLOR} ${aurtargets[@]}"
  fi
  if [[ $pacmandepends ]]; then
    IFS=$'\n' read -rd '' -a pacmandepends < \
      <(printf "%s\n" "${pacmandepends[@]}" | sort -u)
    echo -e "${COLOR6}Pacman Targets (${#pacmandepends[@]}):${ENDCOLOR} ${pacmandepends[@]}"
  fi

  # Sanity check
  totalcount="$((${#aurdepends[@]}+${#aurtargets[@]}+${#pacmandepends[@]}))"
  if [ "$totalcount" = "0" ]; then
    echo -e "${COLOR5}==>$ENDCOLOR nothing to do"; exit 0;
  fi

  # Prompt to proceed
  [[ $buildonly = 1 ]] && phrasing="building" || phrasing="installation"
  echo -en "\nProceed with ${phrasing}? [Y/n] "
  if ! [[ $noconfirm ]]; then
    proceed || exit
  else
    echo
  fi

  # Install pacman dependencies
  if [[ $pacmandepends ]]; then
    if [[ $buildonly = 1 ]]; then
      downfile=$($PACMAN -Sp -- "${pacmandepends[@]}" | awk -v dir=$downdir -F "/" '{print dir"/"$NF}')
      bundle+=("${downfile}")
    fi
    runasroot $PACMAN --noconfirm --asdeps -S -- "${pacmandepends[@]}" || err "Installation failed."
  fi 

  # Install aur dependencies
  if [[ $aurdepends ]]; then
    for dep in "${aurdepends[@]}"; do
      checkcache "$dep" "dependency"
    done
  fi 

  # Install the aur packages
  for package in "${aurtargets[@]}"; do
    scrapeaurdeps "$package"
    if $pacmanbin -T "${dependencies[@]}" &>/dev/null; then
      checkcache "$package" "explicit"
    else
      echo "Dependencies for \`$package' are not met, not building..."
    fi
  done

  # Remove build dependencies
  if [[ $buildonly = 1 ]]; then
    purgedeps+=("${pacmandepends[@]}")
  fi
  if [[ $purgedeps ]]; then
    purgedepends=( $(echo -e "${purgedeps[*]}" | sort -u) )
    runasroot $pacmanbin --noconfirm -Ru -- "${purgedepends[@]}" 2>/dev/null
  fi
  listbundle
}

run_quick_check() {
  bigurl="$RPCURL=multiinfo"
  for p in $($pacmanbin -Qqm); do
    bigurl="$bigurl&arg\[\]=$p"
  done
  parsed_aur="$(curl -s "$bigurl" | \
    jshon -e results -a -e Name -u -p -e Version -u | \
    sed 's/^$/-/' | paste -s -d '\t\n' | sort)"
  packages="$(expac -Q '%n\t%v' | sort)"
  comm -23 <(echo "$parsed_aur") <(echo "$packages") | cut -f 1
  if [[ $auronly == 1 ]]; then
    return
  fi
  # see https://mailman.archlinux.org/pipermail/pacman-dev/2011-October/014673.html
  # (note to self, get that merged already...)
  if [[ -z $CHECKUPDATE_DB ]]; then
    CHECKUPDATE_DB="${TMPDIR:-/tmp}/checkup-db-${USER}/"
  fi
  eval $(awk '/DBPath/ {print $1$2$3}' $pacmanconf)
  DBPath="${DBPath:-/var/lib/pacman/}"
  mkdir -p "$CHECKUPDATE_DB"
  ln -s "${DBPath}/local" "$CHECKUPDATE_DB" &> /dev/null
  fakeroot $pacmanbin -Sqy --dbpath "$CHECKUPDATE_DB" &> /dev/null
  $pacmanbin -Qqu --dbpath "$CHECKUPDATE_DB" 2> /dev/null 
}

# proceed with installation prompt
proceed() {
  read -n 1
  echo
  case "$REPLY" in
    'Y'|'y'|'') return 0 ;;
    *)          return 1 ;;
  esac
}

# process busy loop
nap() {
  while (( $(jobs | wc -l) >= 8 )); do
    jobs > /dev/null
  done
}

# Wrap pacman parameters
pacwrap() {
  if [[ $1 = -Q* ]]; then
    $pacmanbin "$@";
  else
    runasroot $pacmanbin "$@";
  fi;
  exit 0;
}

# Argument parsing
[[ $1 ]] || usage
packageargs=()
while [[ $1 ]]; do
  case "$1" in
    '-S') option=install ;;
    '-Ss') option=search ;;
    '-Ssq'|'-Sqs') option=search ; quiet='1' ;;
    '-Si') option=info ;;
    -S*u*) option=update ; pacmanarg="$1" ;;
    '-G') option=download ;;
    -L*) option=list ; pacmanarg="${1//-L}" ;;
    '--auronly') auronly='1' ; unset noaur ;;
    '--buildonly') buildonly='1' ;;
    '--cachevcs') cachevcs='1' ;;
    '--config') config='1' ; apacmanconf="$2" ; shift ;;
    '--devel') devel='1' ;;
    '--ignore') ignorearg="$2" ; PACOPTS+=("--ignore" "$2") ; shift ;;
    '--ignorearch') MAKEPKGOPTS+=("--ignorearch");;
    '--needed') needed='1' PACOPTS+=("--needed");;
    '--noaur') noaur='1' ; unset auronly ;;
    '--noconfirm') noconfirm='1' PACOPTS+=("--noconfirm");;
    '--noedit') noedit='1' ;;
    '--nofail') nofail='1' ;;
    '--nosource') nosource='1' ;;
    '--preview') preview='1' ;;
    '--purgebuild') purgebuild='1' ;;
    '--quickcheck') quickcheck='1' ;;
    '--quiet') quiet='1' ;;
    '--skipcache') skipcache='1' ;;
    '--skipinteg') skipinteg='1' ; MAKEPKGOPTS+=("--skipinteg");;
    '--skiptest') skiptest='1' ; MAKEPKGOPTS+=("--nocheck");;
    '--warn') warn='1' ;;
    '-h'|'--help') usage ;;
    '-v'|'--verbose') verbose='1' ;;
    '-V'|'--version') version ;;
    '--') shift ; packageargs+=("$@") ; break ;;
    -D*) pacwrap "$@" ;;
    -Q*) pacwrap "$@" ;;
    -R*) pacwrap "$@" ;;
    -S*) pacwrap "$@" ;;
    -T*) pacwrap "$@" ;;
    -U*) pacwrap "$@" ;;
    -*) invalid "$@" ;;
    *) packageargs+=("$1") ;;
  esac
  shift
done

# Override defaults
sourceapacmanconf

# Determine architecture
makearch=$(grep ^CARCH= "$makepkgconf" 2>/dev/null | grep -o -e =.*[0-9A-Za-z] | sed 's/^="//');

# Check for new packages
if [[ $quickcheck == 1 ]]; then
  run_quick_check
  exit
fi

# Sanity checks
[[ $verbose || $debug ]] && infoconf
[[ $config && -z $apacmanconf ]] && err "${COLOR7}error:${ENDCOLOR} no config file specified (use -h for help)"
[[ $option ]] || option="searchinstall"
[[ $option != "list" && $option != "update" && -z $packageargs ]] && err "${COLOR7}error:${ENDCOLOR} must specify a package."
[[ $auronly && $noaur ]] && err "Parameters --auronly and --noaur conflict."

# List (-L) handling
if [[ $option = list ]]; then
  getlistpackages
  exit
fi

# Install (-S) handling
if [[ $option = install ]]; then
  installhandling "${packageargs[@]}"
  exit
fi

# Update (-Su) handling
if [[ $option = update ]]; then
  getignoredpackages
  sourcemakepkgconf
  # Pacman update
  if ! [[ $auronly ]]; then
    runasroot $PACMAN "${PACOPTS[@]}" "$pacmanarg"
  fi

  # Aur update
  total=0
  if ! [[ $noaur ]]; then
    echo -e "${COLOR5}:: ${COLOR1}Synchronizing aur database...${ENDCOLOR}"
    IFS=$'\n' read -rd '' -a packages < <($pacmanbin -Qm)
    newpackages=()
    checkignores=()
    total="${#packages[@]}"
    grep -q '^ *ILoveCandy' "$pacmanconf" && bartype='candy' || bartype='normal'
  fi

  if [[ $devel ]]; then
    for ((i=0; i<$total; i++)); do 
      aurbar "$((i+1))" "$total" "$bartype"
      pkg="${packages[i]%% *}"
      if isignored "$pkg"; then
        checkignores+=("${packages[i]}")
        continue
      fi
      pkginfo "$pkg" &
      nap
    done
    wait
    for ((i=0; i<$total; i++)); do 
      pkg="${packages[i]%% *}"
      ver="${packages[i]##* }"
      if [[ ! -s "$tmpdir/$pkg.PKGBUILD" ]]; then
        continue
      fi
      if isignored "$pkg"; then
        continue
      fi
      unset _darcstrunk _cvsroot _gitroot _svntrunk _bzrtrunk _hgroot
      parser "$tmpdir/$pkg.PKGBUILD"
      if [[ "$(LC_ALL=C vercmp "$pkgver-$pkgrel" "$ver")" -gt 0 ]]; then
        newpackages+=("$pkg")
      elif [[ ${_darcstrunk} || ${_cvsroot} || ${_gitroot} || ${_svntrunk} || ${_bzrtrunk} || ${_hgroot} ]]; then 
        newpackages+=("$pkg")
      fi
    done
  else
    for ((i=0; i<$total; i++)); do 
      aurbar "$((i+1))" "$total" "$bartype"
      pkg="${packages[i]%% *}"
      rpcinfo "$pkg" &
      nap
    done
    wait
    for ((i=0; i<$total; i++)); do
      pkg="${packages[i]%% *}"
      ver="${packages[i]##* }"
      if isignored "$pkg"; then
        checkignores+=("${packages[i]}")
      elif aurversionisnewer "$pkg" "$ver"; then
        newpackages+=("$pkg")
    fi
    done
  fi
  echo

  [[ $noaur ]] || echo -e "${COLOR5}:: ${COLOR1}Starting full aur upgrade...${ENDCOLOR}"

  # Check and output ignored package update info
  for package in "${checkignores[@]}"; do
    if aurversionisnewer "${package%% *}" "${package##* }"; then
      echo -e "${COLOR6}warning:${ENDCOLOR} ${package%% *}: ignoring package upgrade (${package##* } => $aurversion)"
    fi
  done

  # Now for the installation part
  if [[ $newpackages ]]; then
    auronly='1'
    installhandling "${newpackages[@]}"
  fi
  [[ $noaur ]] || echo " local database is up to date"
fi

# Download (-G) handling
if [[ $option = download ]]; then
  for package in "${packageargs[@]}"; do
    if ! [[ $noaur ]] && existsinaur "$package"; then
      pkglist+=("$package")
    elif ! [[ $auronly ]] && existsinpacman "$package"; then
      abslist+=("$package")
    elif [[ $noaur ]]; then
      err "Package \`$package' does not exist in ABS."
    elif [[ $auronly ]]; then
      err "Package \`$package' does not exist in AUR."
    else
      err "Package \`$package' does not exist in ABS+AUR."
    fi
  done

  [[ $abslist ]] && echo -e "${COLOR6}notice:$ENDCOLOR sourcing from ${COLOR4}[ABS]$ENDCOLOR"
  for package in "${abslist[@]}"; do
    pkgrepo=$(absrepo "$package")
    abslink "$pkgrepo" "$package"
    [ -d "$package" ] && rm -r "$package"
    mv "$pkgrepo/$package" "$package"
    rmdir "$pkgrepo"
    ls "$package" | awk -v package="$package" '{print package"/"$0}'
  done

  [[ $pkglist ]] && echo -e "${COLOR6}notice:$ENDCOLOR sourcing from ${COLOR3}[AUR]$ENDCOLOR"
  for package in "${pkglist[@]}"; do
    curl -Lfs "$(pkglink $package)" > "$package.tar.gz"
    [ -d "$package" ] && rm -r "$package"
    mkdir "$package"
    tar xvf "$package.tar.gz" -C "$package" --strip-components=1
  done
fi

# Search (-Ss) handling
if [[ $option = search || $option = searchinstall ]]; then
  # Pacman searching 
  if ! [[ $auronly ]]; then
    if [[ $quiet ]]; then
      results="$($pacmanbin -Ssq -- "${packageargs[@]}")"
    else
      results="$($pacmanbin -Ss -- "${packageargs[@]}")"
      results="$(sed -r "s|^[^ ][^/]*/|$S${COLOR3}&$S${COLOR1}|" <<< "$results")"
      results="$(sed -r "s|^([^ ]+) ([^ ]+)(.*)$|\1 $S${COLOR2}\2$S${ENDCOLOR}\3|" <<< "$results")"
    fi
    if [[ $option = search ]]; then
      echo -e "$results" | fmt -"$_WIDTH" -s
    else  # interactive
      echo -e "$results" | fmt -"$_WIDTH" -s | nl -v 0 -w 1 -s ' ' -b 'p^[^ ]'
    fi | sed '/^$/d'
    pacname=( $($pacmanbin -Ssq -- "${packageargs[@]}") )
    pactotal="${#pacname[@]}"
  else
    pactotal=0
  fi

  # Aur searching and tmpfile preparation
  if ! [[ $noaur ]]; then
    for package in "${packageargs[@]}"; do
      curl -LfGs --data-urlencode "arg=$package" "$RPCURL=search" | \
      jshon -Q -e results -a -e Name -u -p -e Version -u -p -e NumVotes -u -p -e Description -u | \
      sed 's/^$/-/' |  paste -s -d "\t\t\t\n" | sort -nr -k 3 > "$tmpdir/$package.search" &
    done
    wait
    cp "$tmpdir/${packageargs[0]}.search" "$tmpdir/search.results"
    for ((i=1 ; i<${#packageargs[@]} ; i++)); do
      grep -xFf "$tmpdir/search.results" "$tmpdir/${packageargs[$i]}.search" > "$tmpdir/search.results-2"
      mv "$tmpdir/search.results-2" "$tmpdir/search.results"
    done
    sed -i '/^$/d' "$tmpdir/search.results"

    # Prepare tmp file and arrays
    IFS=$'\n' read -rd '' -a aurname < <(cut -f 1 "$tmpdir/search.results")
    aurtotal="${#aurname[@]}"
    alltotal="$(($pactotal+$aurtotal))"
  else
    alltotal="$pactotal"
  fi

  # Echo out the -Ss formatted package information

  IFS=$'\t\n'
  if [[ $option = search ]]; then
    if [[ $quiet ]]; then
      printf "%s\n" ${aurname[@]}
    elif [[ -s "$tmpdir/search.results" ]]; then
      printf "${COLOR3}aur/${COLOR1}%s ${COLOR2}%s${ENDCOLOR} (%s)\n    %s\n" $(cat "$tmpdir/search.results")
    fi
  else
    # interactive
    if [[ $quiet ]]; then
      nl -v ${pactotal:-0} -w 1 -s ' ' <(cut -f 1 "$tmpdir/search.results")
    elif [[ -s "$tmpdir/search.results" ]]; then
      printf "%d ${COLOR3}aur/${COLOR1}%s ${COLOR2}%s${ENDCOLOR} (%s)\n    %s\n" $(nl -v ${pactotal:-0} -w 1 < "$tmpdir/search.results")
    fi
  fi | fmt -"$_WIDTH" -s
  unset IFS

  # Prompt and install selected numbers
  if [[ $option = searchinstall ]]; then
    pkglist=()
    allpackages=( "${pacname[@]}" "${aurname[@]}" )

    # Exit if there are no matches
    [[ $allpackages ]] || exit

    # Prompt for numbers
    echo
    echo -e "${COLOR2}Type numbers to install. Separate each number with a space.${ENDCOLOR}"
    echo -ne "${COLOR2}Numbers: ${ENDCOLOR}"
    read -r
    
    # Parse answer
    if [[ $REPLY ]]; then
      for num in $REPLY; do
        if [[ $num -lt $alltotal ]]; then
          pkglist+=("${allpackages[$num]}")
        else
          err "Number \`$num' is not assigned to any of the packages."
        fi
      done
    fi

    # Call installhandling to take care of the packages chosen 
    installhandling "${pkglist[@]}"
  fi

  # Remove the tmpfiles
  rm -f "$tmpdir/*search" &>/dev/null
  rm -f "$tmpdir/search.result" &>/dev/null
  exit
fi

# Info (-Si) handling
if [[ $option = info ]]; then
  # Pacman info check
  sourcemakepkgconf
  for package in "${packageargs[@]}"; do
    if ! [[ $auronly ]] && existsinpacman "$package"; then
      results="$($pacmanbin -Si -- "$package")"
      results="$(sed -r "s|^(Repository[^:]*:)(.*)$|\1$S${COLOR3}\2$S${ENDCOLOR}|" <<< "$results")"
      results="$(sed -r "s|^(Name[^:]*:)(.*)$|\1$S${COLOR1}\2$S${ENDCOLOR}|" <<< "$results")"
      results="$(sed -r "s|^(Version[^:]*:)(.*)$|\1$S${COLOR2}\2$S${ENDCOLOR}|" <<< "$results")"
      results="$(sed -r "s|^(URL[^:]*:)(.*)$|\1$S${COLOR4}\2$S${ENDCOLOR}|" <<< "$results")"
      results="$(sed -r "s|^[^ ][^:]*:|$S${COLOR1}&$S${ENDCOLOR}|" <<< "$results")"
      echo -e "$results"
      exit
    elif ! [[ $noaur ]]; then # Check to see if it is in the aur
      pkginfo "$package" "$preview"
      [[ -s "$tmpdir/$package.PKGBUILD" ]] || err "${COLOR7}error:${ENDCOLOR} package '$package' was not found"
      parser "$tmpdir/$package.PKGBUILD"

      # Echo out the -Si formatted package information
      # Retrieve each element in order and echo them immediately
      echo -e "${COLOR1}Repository     : ${COLOR3}aur"
      echo -e "${COLOR1}Name           : $pkgname"
      echo -e "${COLOR1}Version        : ${COLOR2}$pkgver-$pkgrel"
      echo -e "${COLOR1}URL            : ${COLOR4}$url"
      echo -e "${COLOR1}Licenses       : ${ENDCOLOR}${license[@]}"
      echo -e "${COLOR1}Groups         : ${ENDCOLOR}${groups[@]:-None}"
      echo -e "${COLOR1}Provides       : ${ENDCOLOR}${provides[@]:-None}"
      echo -e "${COLOR1}Depends On     : ${ENDCOLOR}${depends[@]}"
      echo -e "${COLOR1}Make Depends   : ${ENDCOLOR}${makedepends[@]}"
      echo -e -n "${COLOR1}Optional Deps  : ${ENDCOLOR}"

      len="${#optdepends[@]}"
      if [[ $len -eq 0 ]]; then
        echo "None"
      else
        for ((i=0 ; i<$len ; i++)); do
          if [[ $i = 0 ]]; then
            echo "${optdepends[$i]}"
          else
            echo -e "                 ${optdepends[$i]}" 
          fi
        done
      fi

      echo -e "${COLOR1}Conflicts With : ${ENDCOLOR}${conflicts[@]:-None}"
      echo -e "${COLOR1}Replaces       : ${ENDCOLOR}${replaces[@]:-None}"
      echo -e "${COLOR1}Architecture   : ${ENDCOLOR}${arch[@]}"
      echo -e "${COLOR1}Description    : ${ENDCOLOR}$pkgdesc"
      echo
    else
      err "${COLOR7}error:${ENDCOLOR} package '$package' was not found"
    fi
  done
fi
